### ISSUE TITLE
is there an HELM chart available? 

### ISSUE THREAD

**Issue by syncush** [openblocks-dev/openblocks#38]
Hi, I would like to test openblocks in my company's Kubernetes cluster (OCP to be specific), is there a helm chart available to use? 

if not, I would be happy to contribute one.

**Comment by hanshuai** [comment]
There is currently no helm chart available. It would be great if you could contribute one!

**Comment by y086300** [comment]
@hanshuai will the app be fine if entrypoint.sh would not contain chown on /run directory?
It can be used by Kubernetes for instance to mount secrets so /run/secrets/ can be a read-only path. This makes current openblocks image to fail to start on my k8s platforms.

Other then that the Chart should be rather short and simple.

**Comment by swright-eti** [comment]
I ran into this same problem when I started testing the chart. OpenBlocks is really great, but if I can't run it in a cluster I wont be able to use it. Could we get this on the road map as soon as possible?

```
(⎈|beta:openblocks)swright@dev-09:~/workspace/helm-charts/third-party-charts/openblocks$ k   logs -f openblocks-78bc586f8f-kjr8n
Init mongoDB
Init configuration
yml configuration not exist
Starting with UID : 9001
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/namespace': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/ca.crt': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/token': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..data': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_02_20_46_49.3615641076/namespace': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_02_20_46_49.3615641076/ca.crt': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_02_20_46_49.3615641076/token': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_02_20_46_49.3615641076': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount': Read-only file system
```

**Comment by neon-balcony** [comment]
Hi @swright-eti,

Got it! We will check this issue with our operation engineer and try to fix it soon, please stay tuned.

**Comment by y086300** [comment]
@neon-balcony wasn't that actually fixed in this https://github.com/openblocks-dev/openblocks/pull/68 PR, but overwritten shortly before 1.1.1 release?
I'm not sure what was wrong with that fix.

**Comment by neon-balcony** [comment]
Hi @swright-eti @y086300,

After checking with our engineers it should be a merging mistake, we'll fix that in the next release. Sorry about the back and forth changes and thanks for your patience.

**Comment by lmx1117** [comment]
Hi everyone, this issue is already solved, please check it out, and thanks again for your advice and patience. 😉

**Comment by swright-eti** [comment]
I have updated my chart to use the 1.1.2 tag. I am still getting the same issue where the application is trying to change permission of these files:

```
(⎈|beta:openblocks)swright@dev-09:~/workspace/helm-charts/third-party-charts/openblocks$ k logs -f openblocks-85f564b7dd-9wgng
Init mongoDB
Init configuration
yml configuration not exist
Starting with UID : 9001
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/namespace': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/ca.crt': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/token': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..data': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_09_13_06_35.3176938755/ca.crt': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_09_13_06_35.3176938755/token': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_09_13_06_35.3176938755/namespace': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount/..2022_12_09_13_06_35.3176938755': Read-only file system
chown: changing ownership of '/run/secrets/kubernetes.io/serviceaccount': Read-only file system
```

**Comment by neon-balcony** [comment]
Sorry 😭 , our operation engineers are looking into this... @swright-eti

**Comment by jerry-goodman** [comment]
Hi @swright-eti, We have just fixed this bug, please use the latest image and check it out.

**Comment by swright-eti** [comment]
I have deployed to this to a cluster. The deployment succeeds in that I dont see the ownership changes. The app is running, but there is another problem. I need to be able to set the context root for the web application. The ingress is configured to listen on `/openblocks`. When I go to the URL `https://beta1.dev.eti.software/openblocks` all I see is a spinning graphic. I think the reason for this is that the browser is trying to load Javascript files from `https://beta1.dev.eti.software/` instead of `https://beta1.dev.eti.software/openblocks`

Is there an environment variable I can set to configure the context root?

![image](https://user-images.githubusercontent.com/296522/207895375-ec7c38a8-2ca2-44b7-83e6-f2d77f56c551.png)

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

> When I go to the URL https://beta1.dev.eti.software/openblocks all I see is a spinning graphic. I think the reason for this is that the browser is trying to load Javascript files from https://beta1.dev.eti.software/ instead of https://beta1.dev.eti.software/openblocks

True, currently we don't support a extra path for Openblock deployment, please try using a specific domain with routing from root for Openblocks.
